services:
  - type: web
    name: utang-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_sqlite:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_PATH
        value: /opt/render/project/src
