services:
  - type: web
    name: utang-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_sqlite:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
